"use strict";
let normalx = 'Hola';
normalx = 10;
normalx = true;
let usuario = 20;
console.log(normalx);
let nombre = 'Juan';
nombre = 'Juan Carlos';
//nombre = null
console.log(nombre);
let value;
console.log(value);
value = true;
value = 10;
value = 'hola';
value = {};
value = [];
value = null;
value = undefined;
console.log(value);
let miValor;
console.log('Tipo Unknow', miValor);
let value1 = miValor;
let value2 = miValor;
// let value3: boolean = miValor; 
// let value4: number = miValor; 
const edad = 18;
console.log('Edad', edad);
console.log('Edad' + edad);
const sueldo = 1.234;
const total = 0;
console.log('Sueldo', sueldo);
console.log('Total', total);
const personaje = "El Chavo";
const otroPersonaje = 'Don Ramon';
const otroMas = 'Profesor Jirafales y ${personaje}';
console.log(otroMas);
const heroe = "DeadPool's House";
console.log(heroe);
console.log(heroe.toLowerCase());
let vengador;
vengador = 'Dr strage';
console.log(vengador.chatAt(4));
vengador = 150.55;
console.log(vengador.toFixed(1));
